name: EE - Continuous Integration (CI)

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install, build and test
        run: |
          yarn install
          yarn build
          yarn test
